# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='app',
            name='s',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
