# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180706_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='containers_op_list',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
